### ISSUE TITLE
Paludisme et Maladies fébriles graves

### ISSUE THREAD

**Issue by madjiyangue** [SwissTPH/cdss_tchad#103]
Vignette 002 : 
[maladies fébriles Paludisme Méningite etc.xlsx](https://github.com/SwissTPH/cdss_tchad/files/11990569/maladies.febriles.Paludisme.Meningite.etc.xlsx)
Test correct

**Comment by madjiyangue** [comment]
vignette 003 : 
[maladies fébriles Paludisme Méningite etc.xlsx](https://github.com/SwissTPH/cdss_tchad/files/11990611/maladies.febriles.Paludisme.Meningite.etc.xlsx)
Test correct surtout pour les hypothèses de diagnostic probable.

**Comment by madjiyangue** [comment]
Vignette 004 : 
[maladies fébriles Paludisme Méningite etc.xlsx](https://github.com/SwissTPH/cdss_tchad/files/11990690/maladies.febriles.Paludisme.Meningite.etc.xlsx)
Observations : 
Symptômes 
Méningite : "Examiner si la fontanelle est bombée" devrait être afficher si l'enfant a moins de 2 ans mais si l'enfant a plus de 2 ans, cette question devrait être masquée.
Action : Veiller masquer la question ci-dessus si l'âge de l'enfant est plus de 2 ans.

**Comment by madjiyangue** [comment]
vignette 005 : 
[maladies fébriles Paludisme Méningite etc.xlsx](https://github.com/SwissTPH/cdss_tchad/files/11990769/maladies.febriles.Paludisme.Meningite.etc.xlsx)
Diagnostic : Paludisme neurologique ; est correct

**Comment by madjiyangue** [comment]
Vignette 006 : 
[maladies fébriles Paludisme Méningite etc.xlsx](https://github.com/SwissTPH/cdss_tchad/files/11990808/maladies.febriles.Paludisme.Meningite.etc.xlsx)
Processus de déroulement de l'interrogatoire est correct.

**Comment by madjiyangue** [comment]
Vignette 007 : 
[maladies fébriles Paludisme Méningite etc.xlsx](https://github.com/SwissTPH/cdss_tchad/files/11990829/maladies.febriles.Paludisme.Meningite.etc.xlsx)
Le processus de déroulement de l'interrogatoire devant conduire au diagnostic de Méningite (paludisme exclu) est correct.

**Comment by madjiyangue** [comment]
Vignette 008 : 
[maladies fébriles Paludisme Méningite etc.xlsx](https://github.com/SwissTPH/cdss_tchad/files/11990847/maladies.febriles.Paludisme.Meningite.etc.xlsx)
Traitement de paludisme neurologique : Dosage incorrect
Action : Veiller introduire une bonne formule de dosage d'Artésunate IV car le dosage affiché n'est pas correct.

**Comment by delcroip** [comment]
fontanelle et Arte doivent être bon

**Comment by madjiyangue** [comment]
Corrigé et correct
