### ISSUE TITLE
Malnutrition

### ISSUE THREAD

**Issue by madjiyangue** [SwissTPH/cdss_tchad#105]
Vignette 001 : 
[Vignette Malnutrition enfant (2).xlsx](https://github.com/SwissTPH/cdss_tchad/files/12001994/Vignette.Malnutrition.enfant.2.xlsx)
Observation : le diagnostic de "Maladie fébrile" figurant parmi les diagnostics corrects (Malnutrition aiguë sévère avec complication), Infections des voies respiratoires supérieures et pas d'hypoglycémie) doit être désactiver de la liste des diagnostics.
Action : Désactiver le diagnostic de "maladie fébrile" parmi les restes considérés corrects.

**Comment by madjiyangue** [comment]
Vignette 002 : 
[Vignette Malnutrition enfant (2).xlsx](https://github.com/SwissTPH/cdss_tchad/files/12002129/Vignette.Malnutrition.enfant.2.xlsx)
Observation : Même observation pour maladie fébrile
Action : Diagnostic de maladie fébrile à désactiver et considérer comme fausse.

**Comment by madjiyangue** [comment]
Vignette 003 : 
[Vignette Malnutrition enfant (2).xlsx](https://github.com/SwissTPH/cdss_tchad/files/12002266/Vignette.Malnutrition.enfant.2.xlsx)
Observation la même pour "Maladie fébrile" à corriger/désactiver.

**Comment by madjiyangue** [comment]
Vignette 005 : 
[Vignette Malnutrition enfant (2).xlsx](https://github.com/SwissTPH/cdss_tchad/files/12002663/Vignette.Malnutrition.enfant.2.xlsx)
observation : Faux diagnostic de Maladie fébrile.
Action : veiller le désactiver dans tous les problèmes de malnutrition

**Comment by madjiyangue** [comment]
Vignette 006 : 
[Vignette Malnutrition enfant (2).xlsx](https://github.com/SwissTPH/cdss_tchad/files/12002793/Vignette.Malnutrition.enfant.2.xlsx)
Observation : A moins de 6 mois, le Traitement préventif à la vitamine A n'est pas conseillé puisque l'enfant à 5 mois dans ce cas.
Action : veiller masquer ce traitement préventif pour les moins de 6 mois.

**Comment by madjiyangue** [comment]
Vignette 006 : ok

**Comment by madjiyangue** [comment]
Vignette 008 : 
[Vignette Malnutrition enfant (2).xlsx](https://github.com/SwissTPH/cdss_tchad/files/12002991/Vignette.Malnutrition.enfant.2.xlsx)
Test ok hormis diagnostic "Maladie fébrile" et traitement préventif à la vitamine A" à corriger.

**Comment by madjiyangue** [comment]
Vignette 009 : 
[Vignette Malnutrition enfant (2).xlsx](https://github.com/SwissTPH/cdss_tchad/files/12003626/Vignette.Malnutrition.enfant.2.xlsx)
Test ok hormis la maladie fébrile à corrigé

**Comment by madjiyangue** [comment]
Vignette 010 : 
[Vignette Malnutrition enfant (2).xlsx](https://github.com/SwissTPH/cdss_tchad/files/12003706/Vignette.Malnutrition.enfant.2.xlsx)
Observation : Diagnostic trouvé "Maladie fébrile" qui est un faux diagnostic. Voir capture d'écran pour le bon diagnostic recherché (encerclé en rouge) : 
![image](https://github.com/SwissTPH/cdss_tchad/assets/126242453/04f070d1-d522-4c04-97b6-a1658b6c9918)
Action : veiller corriger le diagnostic en fonction du critère de diagnostic Poids/Taille

**Comment by madjiyangue** [comment]
Vignette 011 : 
[Vignette Malnutrition enfant (2).xlsx](https://github.com/SwissTPH/cdss_tchad/files/12003810/Vignette.Malnutrition.enfant.2.xlsx)
Test Ok hormis le diagnostic de "Maladie fébrile" à corriger.

**Comment by madjiyangue** [comment]
Vignette 012 : 
[Vignette Malnutrition enfant (2).xlsx](https://github.com/SwissTPH/cdss_tchad/files/12003968/Vignette.Malnutrition.enfant.2.xlsx)
Observation : Diagnostic trouvé "Maladie fébrile" qui est un faux diagnostic. Voir capture d'écran pour le bon diagnostic recherché (encerclé en rouge) : 
![image](https://github.com/SwissTPH/cdss_tchad/assets/126242453/4ce44497-bb9e-4052-a8f6-79bdaa24ad28)
Action : veiller corriger le diagnostic et désactiver le diagnostic de "Maladie fébrile"

**Comment by madjiyangue** [comment]
Vignette 014 : 
[Vignette Malnutrition enfant (2).xlsx](https://github.com/SwissTPH/cdss_tchad/files/12004148/Vignette.Malnutrition.enfant.2.xlsx)
Test ok hormis le faux diagnostic surajouté de "Maladie fébrile" à corriger.

**Comment by madjiyangue** [comment]
Vignette 015 : 
[Vignette Malnutrition enfant (2).xlsx](https://github.com/SwissTPH/cdss_tchad/files/12004202/Vignette.Malnutrition.enfant.2.xlsx)
bservation : Diagnostic trouvé "Maladie fébrile" qui est un faux diagnostic. Voir capture d'écran pour le bon diagnostic recherché (encerclé en rouge) : 
![image](https://github.com/SwissTPH/cdss_tchad/assets/126242453/cdd101ef-e5da-4ce5-a0fe-282acfa35f29)
Action : veiller considérer le diagnostic encerclé en rouge et désactiver le faux diagnostic de "Maladie fébrile"

**Comment by delcroip** [comment]
ca doit être bon maintemant

**Comment by madjiyangue** [comment]
Confirmé
