### ISSUE TITLE
Problème généralisée de la peau

### ISSUE THREAD

**Issue by madjiyangue** [SwissTPH/cdss_tchad#116]
Vignettes 001, 002, 003 et 004 : 
[Vignette Éruption généralisée de la peau.xlsx](https://github.com/SwissTPH/cdss_tchad/files/12047495/Vignette.Eruption.generalisee.de.la.peau.xlsx)
Observation : Le faux diagnostic de maladie fébrile apparait dans tous les tests de diagnostics.
Action : Désactiver ou supprimer le faux diagnostic de "Maladie fébrile".

**Comment by delcroip** [comment]
### mm

**Comment by madjiyangue** [comment]
Test confirmé ok
