### ISSUE TITLE
Constipation

### ISSUE THREAD

**Issue by madjiyangue** [SwissTPH/cdss_tchad#117]
Vignettes 001, 002, 003 et 004 : 
[Vignette constipation (2 mois - 5 ans).xlsx](https://github.com/SwissTPH/cdss_tchad/files/12047724/Vignette.constipation.2.mois.-.5.ans.xlsx)
Observation : le faux diagnostic de "Maladie fébrile" apparait partout lors des tests de constipation.
Action : veiller désactiver le faux diagnostic de "Maladie fébrile" partout.

**Comment by delcroip** [comment]
de mm

**Comment by madjiyangue** [comment]
Test confirmé ok
