### ISSUE TITLE
Diarrhée - Déshydratation

### ISSUE THREAD

**Issue by madjiyangue** [SwissTPH/cdss_tchad#118]
Vignette 001, 002, 003, 004, 005, 006, 007, 008, 009, 010, 011 et 012 : 
[Vignette diarrhée - déhsydratation  (2 mois à 5 ans) (Enregistré automatiquement).xlsx](https://github.com/SwissTPH/cdss_tchad/files/12048101/Vignette.diarrhee.-.dehsydratation.2.mois.a.5.ans.Enregistre.automatiquement.xlsx)
Observation : le faux diagnostic de "Maladie fébrile" apparait partout lors les tests.
Action : Veiller désactiver ou supprimer ce faux diagnostic.

**Comment by delcroip** [comment]
doit etre bon

**Comment by madjiyangue** [comment]
Test confirmé ok
