### ISSUE TITLE
Convulsion

### ISSUE THREAD

**Issue by madjiyangue** [SwissTPH/cdss_tchad#120]
Vignette 001, 002, 003, 004, 005, 006, 007, 008 et 009 : 
[Vignette Convulsion (2 mois à 5 ans).xlsx](https://github.com/SwissTPH/cdss_tchad/files/12049899/Vignette.Convulsion.2.mois.a.5.ans.xlsx)
Observation : Le faux diagnostic de maladie fébrile apparait partout pour ce problème de convulsion.
Action : veiller désactiver ce faux diagnostic de maladie fébrile partout où il est.

**Comment by delcroip** [comment]
test ok en PROD (il y avait un second soucis)

**Comment by madjiyangue** [comment]
problème corrigé. Test refait et ok
