### ISSUE TITLE
Test AgHBS et VHC

### ISSUE THREAD

**Issue by madjiyangue** [SwissTPH/cdss_tchad#82]
Vignette 001 à 002 : 
[Vignette AgHBS et VHC.xlsx](https://github.com/SwissTPH/cdss_tchad/files/11060989/Vignette.AgHBS.et.VHC.xlsx)
Les tests de validation ne conduisent pas au diagnostics "Hépatite B et C". La logique est respectée.  Voir capture d'écran : 
![image](https://user-images.githubusercontent.com/126242453/227496387-2ec2ab78-1ec6-42a9-99e1-f81c79f8d600.png)

**Comment by delcroip** [comment]
voir avec nouvelle version

**Comment by madjiyangue** [comment]
Test validé avec la nouvelle version
