### ISSUE TITLE
Signes abdominaux et IST

### ISSUE THREAD

**Issue by madjiyangue** [SwissTPH/cdss_tchad#84]
Vignette 001 et 005 :
[Vignette fièvre typhoïde.xlsx](https://github.com/SwissTPH/cdss_tchad/files/11063503/Vignette.fievre.typhoide.xlsx)
Les tests de validation conduisent à 2 diagnostics "Gonorrhée et Chlamydiose avec complications et suspicion de fièvre typhoïde". Ce dernier diagnostique répond au démarche médicale donc correct.
Action : veillez supprimer/masquer "Gonorrhée et Chlamydiose avec complications".
![image](https://user-images.githubusercontent.com/126242453/227559707-c720f89d-7c2a-4b8b-9174-03aa36a571f7.png)
![image](https://user-images.githubusercontent.com/126242453/227560336-8ab24a12-8d85-4057-b1ff-736b47e98c30.png)
![image](https://user-images.githubusercontent.com/126242453/227560819-9fd85cab-0e1d-4d3e-ac10-2e139a6bd3b1.png)

**Comment by madjiyangue** [comment]
Répétition de diagnostic "Gonorrhée et Chlamydiose avec complication" avec diagnostic "Suspicion de saignement/perforation ulcère gastroduodénal"

**Comment by delcroip** [comment]
soucis de diagnostic sauvage ...

**Comment by madjiyangue** [comment]
"Le diagnostic correct "suspicion de fièvre typhoïde" est enfin apparu sans diagnostic sauvage "Gonorrhée et Chlamydiose avec complications".
Le problème est donc corrigé.

**Comment by madjiyangue** [comment]
Ok
