### ISSUE TITLE
Mal au ventre

### ISSUE THREAD

**Issue by madjiyangue** [SwissTPH/cdss_tchad#86]
Vignette 007 : 
[Vignette mal au ventre.xlsx](https://github.com/SwissTPH/cdss_tchad/files/11064426/Vignette.mal.au.ventre.xlsx)
Le test ne validation ne conduit pas au diagnostic "Sans diagnostic mal au ventre" bien que la logique soit correcte.
Voir capture d'écran : 
![image](https://user-images.githubusercontent.com/126242453/227586411-f5c3730d-2a61-43c8-bf38-54959d19b5c3.png)

**Comment by madjiyangue** [comment]
Il semble que le diagnostic de "CONSTIPATION" n'existe nul part. S'agit-il d'un oubli?

**Comment by delcroip** [comment]
voir dans signes abdominaux (bas droite)
