### ISSUE TITLE
Vignette dépistage VIH

### ISSUE THREAD

**Issue by madjiyangue** [SwissTPH/cdss_tchad#92]
Vignette 001 : 
[11 Vignette Dépistage VIH.xlsx](https://github.com/SwissTPH/cdss_tchad/files/11769280/11.Vignette.Depistage.VIH.xlsx)
Il me semble que les interrogatoires liées au VIH ne sont pas attachées aux problèmes d'infections urinaires donc ça conduit à "Aucun diagnostic trouvé".
Action : Veuillez attacher les interrogatoires sur le VIH aux problèmes urinaires.

**Comment by delcroip** [comment]
la vignette 0001 est pour les ecoulements d'oreille et fonctionne bien

**Comment by madjiyangue** [comment]
Problème corrigé
